Settings:
  Token: "BOT-TOKEN"
  Prefix: "-"
  Storage: "database.db"
  # Enabling DevMode will reset all addon configurations.
  DevMode: false 
  # Verbose mode enables additional debug messages to be shown on the startup log.
  Verbose: true 

Embeds:
  Color: "2f3136"

Branding:
  Name: "BrayanBot"
  Logo: "https://avatars.githubusercontent.com/u/99198112?s=200&v=4"
  Link: "https://brayanbot.dev"

Status:
  Status: "online"
  Afk: false
  Activities:
    - Text: "discord.js"
      Type: "PLAYING"
    - Text: "BrayanBot.dev"
      Type: "STREAMING"
      URL: "https://brayanbot.dev"
    - Text: "for help"
      Type: "LISTENING"
    - Text: "{guild-members} members"
      Type: "WATCHING"
  ActivitiesSettings:
    Order: "normal"
    Interval: 3
